apiVersion: v1
kind: Namespace
metadata:
  name: file-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-api-deployment
  namespace: file-api
  labels:
    app.kubernetes.io/name: file-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: file-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: file-api
    spec:
      containers:
      - name: file-api
        image: local/file-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: file-api-service
  namespace: file-api
spec:
  selector:
    app.kubernetes.io/name: file-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-api-ingress
  namespace: file-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: fileapi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: file-api-service
                port:
                  number: 8080